# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node
#       - image: mysql:8.0
#         environment:
#           MYSQL_ROOT_PASSWORD: calory20
#           MYSQL_DATABASE: shoopers_test
#           MYSQL_USER: root

#     working_directory: ~/Shopmate-Turing
#     steps:
#       - checkout
#       - run:
#           name: Wait for DB
#           # preinstalled in circleci/* docker image
#           command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

#       - run: yarn install
 
#       - run: yarn test

# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8
      - image: circleci/mysql:8.0.16
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: calory20
          MYSQL_DATABASE: shoopers_test
          MYSQL_USER: root


      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/Shopmate-Turing

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Setup Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test



